on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Remode dependecies
        run: rm package-lock.json

      - name: install dependecies
        run: npm ci
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: build project
        run: npm run build
